### ISSUE TITLE
Tech Stack Changes/Updates

### ISSUE THREAD

**Issue by zeferinix** [zeferinix/GraphQL-Starter#57]
This project has been based on my experience and opinions so far and it's time to revisit this again 🙂 

- [x] Move from `npm` to `pnpm` (#58)
- [x] Drop `ObjectionJS` and `Knex` in favor of `Prisma` (for migrations) and `Kysely` (query builder) (#64) 
- [x] Drop `yup` in favor of `zod` (#64) 
- [x] Upgrade to TypeScript 5 (#62)
- [x] Upgrade to Apollo Server v4 (#65)
- [x] Upgrade SuperTokens to latest version (#66)
- [x] Drop `inquirer` and `hygen` (#61)
- [x] Drop `commitlint` (#59)
- [x] Drop `standard-version` (https://github.com/zeferinix/GraphQL-Starter/pull/60/commits/5eb9d122644eab9aa72f2c7b2b86f31a423d17fb)
- [x] Simplify ESLint rules (#63)
- [x] Implement graceful shutdown (#67)

After everything has been checked above:

- [x] Revisit websockets for GraphQL Subscription (#68)
- [x] Revisit seeding (#71)
- [x] Revisit error handling (#70)
- [x] Revisit `UniqueID` type (#69)
- [x] Introduce tRPC maybe?
  - I guess not since tRPC works best when both the client server are either part of the same app or part of a monorepo.
- [x] Update README and diagram (#72)
